title: Blog, vous avez dit blog ???
author: Vivine Assokane
email: vivine@assokane.fr
description: > # this means to ignore newlines until "baseurl:"
  Blog d'apprentissage

# social links
twitter_username: Vivine # DO NOT include the @ character, or else the build will fail!
github_username:  Pondy007 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
